/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicFilters: typeof import('./src/components/filters/BasicFilters.vue')['default']
    ButtonSetting: typeof import('./src/components/ButtonSetting.vue')['default']
    CameraIcon: typeof import('./src/components/Icons/CameraIcon.vue')['default']
    FolderIcon: typeof import('./src/components/Icons/FolderIcon.vue')['default']
    GenericMapComponent: typeof import('./src/components/GenericMapComponent.vue')['default']
    ImageLibrary: typeof import('./src/components/ImageLibrary.vue')['default']
    ImageLibrarySkeleton: typeof import('./src/components/skeletons/ImageLibrarySkeleton.vue')['default']
    LocalityFilter: typeof import('./src/components/filters/LocalityFilter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MapIcon: typeof import('./src/components/Icons/MapIcon.vue')['default']
    MapModal: typeof import('./src/components/MapModal.vue')['default']
    MapPickerDialog: typeof import('./src/components/MapPickerDialog.vue')['default']
    ObservationFilter: typeof import('./src/components/ObservationFilter.vue')['default']
    ObservationMap: typeof import('./src/components/ObservationMap.vue')['default']
    ObservationRegisterForm: typeof import('./src/components/ObservationRegisterForm.vue')['default']
    ObservationsFilter: typeof import('./src/components/ObservationsFilter.vue')['default']
    PopupNotifier: typeof import('@kyvg/vue3-notification')['Notifications']
    ProccesedObservationsFilter: typeof import('./src/components/filters/ProccesedObservationsFilter.vue')['default']
    ProcessedObservationsFilter: typeof import('./src/components/filters/ProcessedObservationsFilter.vue')['default']
    ScientificNameFilter: typeof import('./src/components/filters/ScientificNameFilter.vue')['default']
    SelectFolder: typeof import('./src/components/SelectFolder.vue')['default']
    SettingsIcon: typeof import('./src/components/Icons/SettingsIcon.vue')['default']
    SpecieDetailsDialog: typeof import('./src/components/SpecieDetailsDialog.vue')['default']
    ZoomedInSelectedImageDialog: typeof import('./src/components/ZoomedInSelectedImageDialog.vue')['default']
  }
}
