/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageLibrary: typeof import('./src/components/ImageLibrary.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    PopupNotifier: typeof import('@kyvg/vue3-notification')['Notifications']
    SelectFolder: typeof import('./src/components/SelectFolder.vue')['default']
  }
}
